### ISSUE TITLE
Getting error while trying to send message to same channel quickly through go routines

### ISSUE THREAD

**Issue by ganeshdipdumbare** [GetStream/stream-chat-go#56] opened 2020-03-04 13:36 UTC
Hello team,
I am getting the following error when I am trying to send the messages on the same channel through goroutines-
Post https://chat-us-east-1.stream-io-api.com/channels/team/5e5e5652eba234fa6855ecd8/message?api_key=<api_key>: readLoopPeekFailLocked: <nil>
Please let me know if some fix is needed from my side or it is not possible to send parallel requests to send messages.

**Comment by tbarbugli** [comment] 2020-03-09 08:08
@ganeshdipdumbare can you share the code that you using to send messages?

**Comment by keyneston** [comment] 2020-03-09 09:26
Hi @ganeshdipdumbare, I'm currently actively working on this repo so super convenient timing 😉

I'll start digging in with what you have provided, but any additional information such as code samples, description of how you are using the API, etc is always appreciated.

Thanks

**Comment by keyneston** [comment] 2020-03-09 12:21
Additionally if you can send information such as the go version `go version` and the commit of `stream-chat-go` that you are using.

**Comment by ganeshdipdumbare** [comment] 2020-03-09 12:54
@keyneston Thanks for the reply.
Yes sure, here are the details-
go version go1.13.4 linux/amd64
github.com/GetStream/stream-chat-go/v2 v2.0.1

So the problem is simple, I am trying to send multiple messages on the same channel(through go routines) And it is failing and giving me the above-mentioned error. I think there is some locking logic at the getstream end which is not allowing me to send the multiple messages at exact same time.

**Comment by keyneston** [comment] 2020-03-09 14:15
There are two open issues with go that result in this error, [one around TLS](https://github.com/golang/go/issues/34066) and [one around server response time](https://github.com/golang/go/issues/31259).

Now then that isn't to say this is or isn't an issue on our side. My guess is that it has something to do with how go is interacting with headers/etc being sent by GetStream's web servers.

**Comment by ganeshdipdumbare** [comment] 2020-03-09 14:53
I will check the issues as well. Thanks for the message.
`func SendMessage(request *proto.SendMessageRequest) (*stream.Message, error) {
	lock.Lock()
	defer lock.Unlock()
	if request.UserId == "" {
		request.UserId = serverUser.ID
	}

	entity := &structures.Message{
		Id:          primitive.NewObjectID(),
		ChannelID:   request.ChannelId,
		Sender:      request.UserId,
		Text:        request.Text,
		Attachments: []structures.Attachment{},
	}

	channels, err := client.QueryChannels(&stream.QueryOption{
		Filter: map[string]interface{}{
			"id":   request.ChannelId,
			"type": chatType,
		},
	})
	if err != nil {
		return nil, err
	}

	if len(channels) == 1 {
		c := channels[0]
		var attachments []*stream.Attachment

		for i := range request.Images {
			var url string

			if rf := request.Images[i].GetRawFile(); rf != nil {
				if url, err = uploadRawFile(c, request.UserId, rf); err != nil {
					return nil, fmt.Errorf("Error uploading raw file %v", err)
				}
			} else {
				url = request.Images[i].GetLink()
			}
			attachments = append(attachments, &stream.Attachment{
				Type:     "image",
				AssetURL: url,
			})
			entity.Attachments = append(entity.Attachments, structures.Attachment{
				Type: "image",
				Link: url,
			})
		}

		for i := range request.Files {
			var url string
			if rf := request.Files[i].GetRawFile(); rf != nil {
				if url, err = uploadRawFile(c, request.UserId, rf); err != nil {
					return nil, fmt.Errorf("Error uploading raw file %v", err)
				}
			} else {
				url = request.Files[i].GetLink()
			}
			attachments = append(attachments, &stream.Attachment{
				Type:     "file",
				AssetURL: url,
			})
			entity.Attachments = append(entity.Attachments, structures.Attachment{
				Type: "file",
				Link: url,
			})
		}

		for i := range request.Notifications {
			attachments = append(attachments, &stream.Attachment{
				Type: "notification",
				ExtraData: map[string]interface{}{
					"link":             request.Notifications[i].Link,
					"text":             request.Notifications[i].Text,
					"notificationType": request.Notifications[i].Type,
				},
			})
			entity.Attachments = append(entity.Attachments, structures.Attachment{
				Type:             "notification",
				NotificationType: request.Notifications[i].Type,
				Text:             request.Notifications[i].Text,
				Link:             request.Notifications[i].Link,
			})
		}

		for i := range request.Forms {
			attachments = append(attachments, &stream.Attachment{
				ExtraData: map[string]interface{}{
					"formId": request.Forms[i].FormId,
				},
			})
			FormID, err := primitive.ObjectIDFromHex(request.Forms[i].FormId)
			if err != nil {
				return nil, err
			}
			entity.Attachments = append(entity.Attachments, structures.Attachment{
				Type:   "form",
				FormId: &FormID,
			})
		}

		message := &stream.Message{
			Text:        request.Text,
			Attachments: attachments,
			ExtraData: map[string]interface{}{
				"visibleFor": request.VisibleFor,
			},
		}
		entity.VisibleFor = request.VisibleFor
		if request.Metadata != nil {
			message.ExtraData["metadata"] = map[string]interface{}{"sendMail": request.Metadata.SendMail}
			entity.Metadata.Sendmail = request.Metadata.SendMail
		}

		message, err = c.SendMessage(message, request.UserId)
		if err == nil {
			entity.MessageID = message.ID
			err = dao.CreateMessage(nil, entity)
		}
		return message, err
	}

	return nil, fmt.Errorf("channel does not exist")
}
`
Maybe this will help you in understanding the issue in better way.
Please ignore the locking logic as it was failing at our end so we have added queue in between.

**Comment by keyneston** [comment] 2020-03-09 15:13
Nothing there immediately screams problem to me. From my quick read it should work as intended without the locking.

Are you doing any setup of the stream client? Setting an HTTP Client? Anything like:

```
client, err := stream.NewClient(apiKey, apiSecret)
client.HTTP = &http.Client{
/stuff here
}
```

Just want to make sure it isn't something like a conflict in behaviour between a custom dialer or tcproundtripper.

**Comment by ganeshdipdumbare** [comment] 2020-03-09 15:39
`var (
	client     *stream.Client
	lock       sync.Mutex
	serverUser = &stream.User{
		ID: "admin",
	}
)

func Initialize() {
	var err error
	client, err = stream.NewClient(env.Get().GetStreamKey, []byte(env.Get().GetStreamSecret))
	if err != nil {
		log.Fatal("init getstream error:", err)
	}
}
`
This is how I implementedthe client initialization.

**Comment by frranck** [comment] 2020-03-17 15:01
Any update on this issue?

**Comment by meerkat-lib** [comment] 2020-03-17 15:07
our first version has no lock, we got this error very frequently.

**Comment by meerkat-lib** [comment] 2020-03-17 15:09
even we create multi clients. I can write unit test for it. will paste it later.

**Comment by meerkat-lib** [comment] 2020-03-17 16:18
I created a simple unit test for sending messages with goroutine:

package service

import (
	"fmt"
	"mcm_chat_service/env"
	"testing"
	"time"

	stream "github.com/GetStream/stream-chat-go/v2"
	"gopkg.in/go-playground/assert.v1"
)

var (
	testClient *stream.Client
)

func init() {
	var err error
	// replace with correct key and secret
	testClient, err = stream.NewClient(env.Get().GetStreamKey, []byte(env.Get().GetStreamSecret))
	if err != nil {
		fmt.Println("init getstream error:", err)
	}
}

func updateUsers(users ...*stream.User) error {
	_, err := testClient.UpdateUsers(users...)
	if err != nil {
		fmt.Println("update users error:", err)
	}
	return err
}

func createChannel(channelID string, users ...*stream.User) error {
	members := []string{}
	for _, user := range users {
		members = append(members, user.ID)
	}

	fmt.Println("creating channel ", channelID)
	_, err := testClient.CreateChannel("team", channelID, "admin", map[string]interface{}{
		"members": members,
	})
	if err != nil {
		fmt.Println("create channel error:", err)
		return err
	}

	return err
}

func sendMessage(channelID, text string) (*stream.Message, error) {
	channels, err := testClient.QueryChannels(&stream.QueryOption{
		Filter: map[string]interface{}{
			"id":   channelID,
			"type": "team",
		},
	})
	if err != nil {
		return nil, err
	}
	if len(channels) == 1 {
		c := channels[0]

		req := &stream.Message{
			Text: text,
		}
		return c.SendMessage(req, "admin")
	}
	return nil, fmt.Errorf("channel does not exist")
}

func TestUpateUser(t *testing.T) {
	err := updateUsers(&stream.User{
		ID: "test",
	}, &stream.User{
		ID: "admin",
	})
	assert.Equal(t, nil, err)
}

func TestCreateChaneel(t *testing.T) {
	err := createChannel("new_channel", &stream.User{
		ID: "test",
	}, &stream.User{
		ID: "admin",
	})
	assert.Equal(t, nil, err)
}

func TestSendMessages(t *testing.T) {
	go send(t)
	go send(t)
	go send(t)

	time.Sleep(time.Second * 3)
}

func send(t *testing.T) {
	_, err := sendMessage("new_channel", "some text")
	assert.Equal(t, nil, err)
}

**Comment by meerkat-lib** [comment] 2020-03-17 16:20
code in play.golang:

https://play.golang.org/p/O9dAubVsZ1Y

**Comment by meerkat-lib** [comment] 2020-03-17 16:20
we got error logs:

getstream_test.go:101 <nil> does not equal Post https://chat-us-east-1.stream-io-api.com/channels/team/new_channel/message?api_key=rpjmjskfy6gx: readLoopPeekFailLocked: <nil>

**Comment by meerkat-lib** [comment] 2020-03-17 16:21
and another issue: (happens without goroutine):

2020/03/17 17:17:33 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nDate: Tue, 17 Mar 2020 16:17:32 GMT\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 20\r\nConnection: close\r\n\r\nInvalid HTTP request"; err=<nil>

**Comment by keyneston** [comment] 2020-04-17 14:22
Not sure how I missed the github notifications on this issue. Was just about to ping you to follow up on the issue.

That looks like a combination timeout/connection pooling issue. I'll see if I can dig more into it.

**Comment by keyneston** [comment] 2020-04-17 15:42
@meerkat-lib still not sure exactly what is going on but your errors seem to match the errors being reported in https://github.com/golang/go/issues/31259.

**Comment by ferhatelmas** [comment] 2022-02-10 22:04
This should be fixed in v5. Please let us know if you still see the problem.

**Closed by ferhatelmas** 2022-02-10 22:04 UTC
Labels: bug
